Debug signUp flow
* Add store
* Add debugging messages to signup flow

After the user signs in with magic, signUp tries to fetch the user profile to ensure that they don't already have an account. Unfortunately, the current version of the API throws a 500 error when you try to fetch a user who does not exist, which seems to trigger an "Unhandled Runtime Error" in the `getProfile` call in the Greenruhm Connect SDK client.

Server error:

```
[GET] /api/profile/0x97fd7ed9320eabb08837741c421c53fa3d1f50f4
15:31:39:27
{
  time: '2022-07-07T22:31:39.409Z',
  body: '""',
  query: '{"profileId":"0x97fd7ed9320eabb08837741c421c53fa3d1f50f4"}',
  method: 'GET',
  headers: '{"host":"greenruhm.com","x-real-ip":"98.147.234.201","x-vercel-proxy-signature-ts":"1657233399","x-vercel-deployment-url":"greenruhm-web-5rqacdiij-paralleldrive.vercel.app","x-vercel-forwarded-for":"98.147.234.201","x-vercel-id":"sfo1::p89b8-1657233099266-1305e2bf09d7","x-forwarded-host":"greenruhm.com","accept":"*/*","x-vercel-ip-country":"US","x-forwarded-proto":"https","x-vercel-proxy-signature":"Bearer b57cd20a5fe9b900f5a5b916e56a5e41c5cbb4eec6209284ad594c8d66382676","x-forwarded-for":"98.147.234.201","user-agent":"curl/7.64.1","forwarded":"for=98.147.234.201;host=greenruhm.com;proto=https;sig=0QmVhcmVyIGI1N2NkMjBhNWZlOWI5MDBmNWE1YjkxNmU1NmE1ZTQxYzVjYmI0ZWVjNjIwOTI4NGFkNTk0YzhkNjYzODI2NzY=;exp=1657233399","x-vercel-ip-city":"Van%20Nuys","x-nextjs-page":"/api/profile/[profileId]","x-vercel-ip-country-region":"CA","connection":"close"}',
  error: true,
  url: '/api/profile/0x97fd7ed9320eabb08837741c421c53fa3d1f50f4?profileId=0x97fd7ed9320eabb08837741c421c53fa3d1f50f4',
  message: 'Set not found.\n' +
    ': {"response":{"errors":[{"message":"Set not found.\\n","extensions":{"code":"instance not found"}}],"status":200},"request":{"query":"\\n  query getProfile($profileId: String!) {\\n    userByWalletAddress(walletAddress: $profileId) {\\n      walletAddress\\n      signupDate\\n      lastSignedIn\\n      username\\n      followCount\\n      displayName\\n      avatarImg\\n    }\\n  }\\n","variables":{"profileId":"0x97fd7ed9320eabb08837741c421c53fa3d1f50f4"}}}',
  stack: 'Error: Set not found.\n' +
    ': {"response":{"errors":[{"message":"Set not found.\\n","extensions":{"code":"instance not found"}}],"status":200},"request":{"query":"\\n  query getProfile($profileId: String!) {\\n    userByWalletAddress(walletAddress: $profileId) {\\n      walletAddress\\n      signupDate\\n      lastSignedIn\\n      username\\n      followCount\\n      displayName\\n      avatarImg\\n    }\\n  }\\n","variables":{"profileId":"0x97fd7ed9320eabb08837741c421c53fa3d1f50f4"}}}\n' +
    '    at GraphQLClient.<anonymous> (/var/task/node_modules/graphql-request/dist/index.js:170:35)\n' +
    '    at step (/var/task/node_modules/graphql-request/dist/index.js:63:23)\n' +
    '    at Object.next (/var/task/node_modules/graphql-request/dist/index.js:44:53)\n' +
    '    at fulfilled (/var/task/node_modules/graphql-request/dist/index.js:35:58)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  requestId: 'cl5blsr9z000309l9373vg801'
}
```

Client Error:

```
Unhandled Runtime Error
TypeError: Failed to fetch

Call Stack:
getProfile src/services/greenruhm-api/index.js (76:23)
```